import React from 'react';
import {
  Camera,
  X,
  Check,
  Minus,
  Sun,
  Moon,
  Laptop,
  Wrench,
  DollarSign,
  BarChart2,
  Edit2,
  Trash2,
  Smartphone,
  BatteryCharging,
  Plug,
  Droplet,
  Package,
  Loader2,
  Search,
  Bell,
  MessageSquare,
  Users,
  User,
  Settings,
  Key,
  Image,
  Truck,
  ClipboardList,
  FolderOpen,
  Tag,
  Percent,
  Layout,
  Receipt,
  Banknote,
} from 'lucide-react';

const ICON_MAP = {
  camera: Camera,
  x: X,
  check: Check,
  minus: Minus,
  sun: Sun,
  moon: Moon,
  laptop: Laptop,
  wrench: Wrench,
  dollar: DollarSign,
  barchart: BarChart2,
  edit: Edit2,
  trash: Trash2,
  smartphone: Smartphone,
  battery: BatteryCharging,
  plug: Plug,
  droplet: Droplet,
  package: Package,
  loader: Loader2,
  search: Search,
  bell: Bell,
  message: MessageSquare,
  users: Users,
  user: User,
  settings: Settings,
  key: Key,
  image: Image,
  truck: Truck,
  clipboard: ClipboardList,
  folder: FolderOpen,
  tag: Tag,
  percent: Percent,
  layout: Layout,
  receipt: Receipt,
  bank: Banknote,
};

const Icon = ({ name, size = 16, stroke = 2, className = '', ...props }) => {
  const Comp = ICON_MAP[name];
  if (!Comp) return null;
  return <Comp size={size} strokeWidth={stroke} className={className} {...props} />;
};

export default Icon;
